name: Factorial tests
on:
  push:
    branches: [lucianopinheirob-patch-1]

jobs:
  test-factorial:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: pip install pytest
    - name: Test factorial function
      run: pytest -v tests/test_factorial.py

